server:
  port: 8080

spring:
  application:
    name: SpringMVCApplication

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mvc_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:/data/*.sql

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  web:
    error:
      whitelabel:
        enabled: false